### ISSUE TITLE
Add gulp task and static folder for json files

### ISSUE THREAD

**Issue by sanjaytwisk** [mirabeau-nl/frontend-boilerplate#58] opened 2017-05-08 08:20 UTC
I propose to add static json to the bootstrap to be able to mock async json fetching. I use it in almost every project and find myself implementing this every time I start with the bootstrap.

**Comment by awolkers** [comment] 2017-05-08 09:48
Agree on this one. I always add a `media` folder within `src` where I put all the non static assets like images and videos served as test content. This folder also contains `.json` and `.html` files used for async fetching of data. A watch task is added to make sure files are copied to the `dist` folder.

**Comment by sanjaytwisk** [comment] 2017-05-08 10:03
I would say that images, video's and json files belong in the `/static` folder. According to your comment I think we should add `json` and `video` tot `src/static` and implement the corresponding gulp tasks. I think the json task should only run in dev mode and the video task should run in both dev and dist.

**Comment by awolkers** [comment] 2017-05-08 11:22
All files used for mocking or content purpose should not be included within the `/src/static` folder. There is no need for them to be in a production environment. Adding a folder directly within `/src` would be a better place for these files. The name for this folder can be something like 'mock' or 'media'.

**Comment by branneman** [comment] 2017-05-08 13:53
Great idea! 👍 

Why not place your json mock files inside the `components` folder, together with the html, css and js? Since the front-end bootstrap is not an actual application itself, a json file isn't any different from a html file for example. All the HTML code we produce is implemented in a server-side application, not used by itself.

The front-end bootstrap environment is basically a static site generator. Sometimes the results are uploaded to a static site host, so a user would expect all the json mock files to be available, otherwise a demo would not function, thereby not having any value as a demo.

I always try to make my json test data component-specific. An example component folder could then be like:

```
src/
  components/
    nav/
      nav.html
      nav.css
      nav.js
      nav.json
```

If you don't want those json files to be automatically released to production, you should do just that: make the build (or backend developer) not simply copy/move those files into production when they shouldn't.

**Comment by awolkers** [comment] 2017-05-08 14:26
Sounds good to put the json files within the components folders but sometimes json are used on a higher scope.
It also leaves us with the problem of where to put the videos and images, etc.

**Comment by branneman** [comment] 2017-05-11 06:24
This issue seems really about json mock data. For images we already have a folder, and videos are an exception I think.

**Comment by peeke** [comment] 2017-05-17 11:06
Maybe we could rename _media_ to _assets_ to allow it to contain a broader range of contenttypes?

**Comment by colin-aarts** [comment] 2019-03-28 08:22
Closing, dupe of #9

**Closed by colin-aarts** 2019-03-28 08:22 UTC
